### ISSUE TITLE
Enhancement: fix-tabs limit by filename ending

### ISSUE THREAD

**Issue by dissolve** [Lucas-C/pre-commit-hooks#22]
certain languages and files are unfortunately very picky about tab characters
makefiles are a prime example, though there are some systems to somewhat fix that in newer versions.

It would be nice to be able to limit the only *.php for example

**Comment by Lucas-C** [comment]
This is already possible! _cf._ https://pre-commit.com/#hooks-exclude

```yaml
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
    -   id: remove-tabs
        exclude: Makefile
```

You can even use types: https://pre-commit.com/#filtering-files-with-types

Does that answer your question?
