### ISSUE TITLE
Matching multiple license headers?

### ISSUE THREAD

**Issue by JoshLind** [Lucas-C/pre-commit-hooks#68]
Hi folks,

Firstly, thanks for building and maintaining this useful tool -- it's great! 😄 One question I have, is there support for matching multiple license files? i.e., check if the license in a file is one of several options? We have use cases where different files require slightly different licenses.

I see that there's support for fuzzy matching (https://github.com/Lucas-C/pre-commit-hooks#fuzzy-license-matching), but it would be great to see if we could support *exact* matching with multiple potential licenses? Does this already exist, or is it something that would require changes? (Apologies if I've missed it!)

Thanks for your help!

**Comment by Lucas-C** [comment]
Hi @JoshLind!

It is actually very simple to have different rules for different files usingn this hook: simply duplicate configuration blocks!
```yaml
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.4.2
    hooks:
      - id: insert-license
        files: \.groovy$
        args:
          - --license-filepath
          - LICENSE
      - id: insert-license
        files: \.java$
        args:
          - --license-filepath
          - LICENSE2
          - --use-current-year
```

Does that answer your use case?

**Comment by JoshLind** [comment]
Hi @Lucas-C!

Thanks for the quick response 😄 If I understand correctly, your example would provide different licenses to files based on type, right? i.e., license 1 for `groovy` files and license 2 for `java` files? Our use-case is different -- all the files will have the same types (and even directory locations), it's just that some will have a different license depending on who helped contribute to and/or write the file.

From a UI perspective, it'd probably look more like:
```
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.4.2
    hooks:
      - id: insert-license
        files: \.rs$ # Rust files
        args:
          - --license-filepath
          - LICENSE1 # The file could have this license
          - --license-filepath
          - LICENSE2 # Or the file could have this license
```

Let me know if what I'm saying doesn't make sense 😃
