### ISSUE TITLE
Is there a way of defining a string in the hooks args instead of --license-filepath

### ISSUE THREAD

**Issue by mikel-brostrom** [Lucas-C/pre-commit-hooks#81]
This:

```
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.3
  hooks:
    - id: insert-license
      files: ./*
      args:
        - --license-filepath
        - LICENSE
        - --use-current-year
```

does not work for me as my LICENSE 600+ lines long and I don't want to add a `txt` file to the repo simply for this. Is there a way of specifying a string to be inserted? Something like

```
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.3
  hooks:
    - id: insert-license
      files: ./*
      args:
        - --license-string
        - "MyName RepoName AGPL3.0 License"
        - --use-current-year
```

?
