### ISSUE TITLE
How do I specify the hook to be applied to all files in the repo that ends with .py?

### ISSUE THREAD

**Issue by mikel-brostrom** [Lucas-C/pre-commit-hooks#82]
I am uncertain of this part here: ` files: ./*.py`.

```
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.3
  hooks:
    - id: insert-license
      files: ./*.py  # ???
```
