### ISSUE TITLE
[Enhancement] Update multiple licence year ends in one run. 

### ISSUE THREAD

**Issue by mdeweerd** [Lucas-C/pre-commit-hooks#94]
I have two lines with the licence year in my headers:

```text
/* Copyright (c) 2012-2023 Dummy             */
/*********************************************/
/* @copyright Copyright (c) 2012-2023 Dummy  */
```

On the first pre-commit execution, the first line is updated.
On the second pre-commit execution, the second line is updated.
On the third run, the commit is performed.

If one of the pre-commit runs could be avoided by changing both lines in a single run that would be great.

This is my configuration:

```yaml
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.1
    hooks:
      - id: insert-license
        files: ^(.*\.(php))$
        args:
          - --license-filepath
          - doc/LICENSE
          - --use-current-year
          - --comment-style
          - ''
          - --no-space-in-comment-prefix
          - --fuzzy-match-extra-lines-to-check
          - '10'
          - --insert-license-after-regex
          - ^<\?php$
```

Note: My licence file is already updated like this:
```text
/* Copyright (c) 2012-2024 Dummy             */
/*********************************************/
/* @copyright Copyright (c) 2012-2024 Dummy  */
```
